# Generated by Django 5.2.7 on 2025-11-14 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('nombre_inscrits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Bureau de vote',
                'verbose_name_plural': 'Bureaux de vote',
                'ordering': ['centre_vote', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='CentreVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Centre de vote',
                'verbose_name_plural': 'Centres de vote',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('candidat', 'Candidat'), ('representant', 'Représentant')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('bureau_vote', models.ForeignKey(blank=True, help_text='Bureau de vote affecté (pour les représentants uniquement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representants', to='myApplication.bureauvote')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='bureauvote',
            name='centre_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='myApplication.centrevote'),
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_prefectures', to='myApplication.departement')),
            ],
            options={
                'verbose_name': 'Sous-préfecture',
                'verbose_name_plural': 'Sous-préfectures',
                'ordering': ['nom'],
                'unique_together': {('nom', 'departement')},
            },
        ),
        migrations.AddField(
            model_name='centrevote',
            name='sous_prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centres_vote', to='myApplication.sousprefecture'),
        ),
        migrations.AlterUniqueTogether(
            name='bureauvote',
            unique_together={('numero', 'centre_vote')},
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_voix', models.IntegerField(help_text='Nombre de voix obtenues', validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_pv', models.ImageField(help_text='Photo du procès-verbal', upload_to='pv_photos/%Y/%m/%d/')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('verifie', models.BooleanField(default=False, help_text="Résultat vérifié par l'administrateur")),
                ('observations', models.TextField(blank=True, null=True)),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='myApplication.bureauvote')),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'candidat'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to=settings.AUTH_USER_MODEL)),
                ('representant', models.ForeignKey(limit_choices_to={'role': 'representant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-date_saisie'],
                'unique_together': {('candidat', 'bureau_vote')},
            },
        ),
    ]
