# Generated by Django 5.2.7 on 2025-11-14 22:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['numero_candidat', 'first_name'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='numero_candidat',
            field=models.IntegerField(blank=True, help_text='Numéro du candidat sur le bulletin de vote', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parti_politique',
            field=models.CharField(blank=True, help_text='Parti politique (pour les candidats)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_votants', models.IntegerField(help_text='Nombre total de votants effectifs', validators=[django.core.validators.MinValueValidator(0)])),
                ('bulletins_nuls', models.IntegerField(default=0, help_text='Nombre de bulletins nuls', validators=[django.core.validators.MinValueValidator(0)])),
                ('bulletins_blancs', models.IntegerField(default=0, help_text='Nombre de bulletins blancs', validators=[django.core.validators.MinValueValidator(0)])),
                ('suffrages_exprimes', models.IntegerField(help_text='Nombre de suffrages exprimés (calculé automatiquement)', validators=[django.core.validators.MinValueValidator(0)])),
                ('photo_pv', models.ImageField(help_text='Photo du procès-verbal officiel', upload_to='pv_photos/%Y/%m/%d/')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('verifie', models.BooleanField(default=False, help_text="PV vérifié par l'administrateur")),
                ('observations', models.TextField(blank=True, null=True)),
                ('bureau_vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proces_verbal', to='myApplication.bureauvote')),
                ('representant', models.ForeignKey(limit_choices_to={'role': 'representant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proces_verbaux_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procès-verbal',
                'verbose_name_plural': 'Procès-verbaux',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='ResultatCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_voix', models.IntegerField(help_text='Nombre de voix obtenues par ce candidat', validators=[django.core.validators.MinValueValidator(0)])),
                ('candidat', models.ForeignKey(limit_choices_to={'role': 'candidat'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultats_obtenus', to=settings.AUTH_USER_MODEL)),
                ('proces_verbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='myApplication.procesverbal')),
            ],
            options={
                'verbose_name': 'Résultat candidat',
                'verbose_name_plural': 'Résultats candidats',
                'ordering': ['-nombre_voix'],
                'unique_together': {('proces_verbal', 'candidat')},
            },
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
    ]
