# Generated by Django 5.2.7 on 2025-12-26 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplication', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevéHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_releve', models.DateTimeField(auto_now_add=True, verbose_name='Heure du relevé')),
                ('nombre_votants', models.IntegerField(help_text='Nombre de votants à cette heure', validators=[django.core.validators.MinValueValidator(0)])),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_horaires', to='myApplication.bureauvote')),
                ('representant', models.ForeignKey(limit_choices_to={'role': 'representant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relevé horaire',
                'verbose_name_plural': 'Relevés horaires',
                'ordering': ['-heure_releve'],
            },
        ),
    ]
